spring:
  application:
    name: mealster
  mvc:
    servlet:
      path: /api
  jpa:
    defer-datasource-initialization: true
    database: h2
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /api/h2-console
      settings:
        web-allow-others: true
logging:
  level:
    org.hibernate: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace